#ifndef _DATA_H
#define _DATA_H

#include "linux/types.h"

/**
 *  This module is automatically generated by the malWASH IDA plugin.
 *  It contains all data necessary to execute the splittet program.
 */

 
#define NBLOCKS 2           // Number of blocks detected by IDA
#define NSEGMS 2            // Number of segments
#define NPROC  1            // Number of processes where we inject the emulator

// Bootstrap code
extern char bootstrap[];
extern size_t bootstraplen;

// Emulator code
extern char emulator[];
extern size_t emulatorlen;

// Segments contained in the program
extern char **supsegm[];
extern unsigned int seglen[];

// Modules needed by the program
extern char modtab[];
extern unsigned int modtablen;

// Function table
extern char funtab[];
extern unsigned int funtablen;

// Thread table
extern unsigned int thdtab[];

// Initialized pointer table
extern int initab[];
extern size_t initablen;

extern size_t blklen[];
extern char *supblk[];
#endif